### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by iakashpaul** [Mefi100feLL/Purchases#1]
I read that you were able to port the peerjs framework to android for native apps. Do you have a repository of that code.
Thanks.

**Comment by Mefi100feLL** [comment]
No. I've done this for a long time. Now I'm using ooVoo for implementing video conferencing.

**Comment by iakashpaul** [comment]
Ok thanks, I have my own peerjs-server setup already. Sadly skyway android sdk isn't opensourced
